class modelworks:

    lotsosets = [[0 for x in range(5)] for y in range(34)]
    lotsosets[0][0] = 'aadi-bioscience'
    lotsosets[0][1] = 'Neil Desai'
    lotsosets[0][2] = 'Bio-pharma'
    lotsosets[0][3] = 'Early Stage Venture'
    lotsosets[0][4] = 'Series A'
    lotsosets[1][0] = 'aagave-assistans'
    lotsosets[1][1] = 'Home Health Care'
    lotsosets[1][2] = 'Sweden'
    lotsosets[1][3] = 'Acquired'
    lotsosets[1][4] = 'Team Olivia AB'
    lotsosets[2][0] = 'aagzil-inc'
    lotsosets[2][1] = 'Neil Desai'
    lotsosets[2][2] = 'Pharmaceutical'
    lotsosets[2][3] = 'Early Stage Venture'
    lotsosets[2][4] = 'Seed'
    lotsosets[3][0] = 'aaipharma-services'
    lotsosets[3][1] = 'Private Equity'
    lotsosets[3][2] = 'Biotechnology'
    lotsosets[3][3] = 'Acquired'
    lotsosets[3][4] = 'Series A'
    lotsosets[4][0] = 'aalto-helsinki'
    lotsosets[4][1] = 'Scandinavia'
    lotsosets[4][2] = 'Genetics'
    lotsosets[4][3] = 'Lab'
    lotsosets[4][4] = 'Bioreactors'
    lotsosets[5][0] = 'aana-american-association-of-nurse-anesthetists'
    lotsosets[5][1] = 'Healthcare'
    lotsosets[5][2] = 'Chicago'
    lotsosets[5][3] = 'Private'
    lotsosets[5][4] = '1931'
    lotsosets[6][0] = 'aandsa-pharm'
    lotsosets[6][1] = 'Life Science'
    lotsosets[6][2] = 'psoriasis'
    lotsosets[6][3] = 'European Union'
    lotsosets[6][4] = 'Cardiff'
    lotsosets[7][0] = 'aapc'
    lotsosets[7][1] = 'Medical Device'
    lotsosets[7][2] = 'Western US'
    lotsosets[7][3] = '1988'
    lotsosets[7][4] = 'Healthcare'
    lotsosets[8][0] = 'abbey-healthcare'
    lotsosets[8][1] = 'Ireland'
    lotsosets[8][2] = 'Private'
    lotsosets[8][3] = 'Medical delivery'
    lotsosets[8][4] = 'Nursing'
    lotsosets[9][0] = 'aarkstore'
    lotsosets[9][1] = 'Mumbai'
    lotsosets[9][2] = 'Healthcare'
    lotsosets[9][3] = '2008'
    lotsosets[9][4] = 'IT'
    lotsosets[10][0] = 'bioscape-digital-2'
    lotsosets[10][1] = 'Stuart Bracken'
    lotsosets[10][2] = 'Health care'
    lotsosets[10][3] = 'Software'
    lotsosets[10][4] = 'Seed'
    lotsosets[11][0] = 'biolucid'
    lotsosets[11][1] = 'Acquired'
    lotsosets[11][2] = 'Healt care'
    lotsosets[11][3] = 'Dale Park'
    lotsosets[11][4] = '3D software platform'
    lotsosets[12][0] = 'biomae'
    lotsosets[12][1] = '850K'
    lotsosets[12][2] = 'Biometrics'
    lotsosets[12][3] = '679.5K'
    lotsosets[12][4] = 'Seed'
    lotsosets[13][0] = 'BioMatrix Specialty Pharmacy'
    lotsosets[13][1] = '80M'
    lotsosets[13][2] = 'East Coast'
    lotsosets[13][3] = '679.5K'
    lotsosets[13][4] = 'Private Equity'
    lotsosets[14][0] = 'biomcare'
    lotsosets[14][1] = 'Denmark'
    lotsosets[14][2] = 'gut microbiota '
    lotsosets[14][3] = 'Scandinavia'
    lotsosets[14][4] = 'Seed'
    lotsosets[15][0] = 'bioscape-digital-2'
    lotsosets[15][1] = 'Stuart Bracken'
    lotsosets[15][2] = 'Health care'
    lotsosets[15][3] = '679.5K'
    lotsosets[15][4] = 'Seed'
    lotsosets[16][0] = 'biomed-laboratories'
    lotsosets[16][1] = 'Acquired'
    lotsosets[16][2] = 'Health care'
    lotsosets[16][3] = 'Medical Device'
    lotsosets[16][4] = '2011'
    lotsosets[17][0] = 'biophos'
    lotsosets[17][1] = 'Erik Nordquist'
    lotsosets[17][2] = 'Medical Device'
    lotsosets[17][3] = '2007'
    lotsosets[17][4] = 'Software'
    lotsosets[17][0] = 'canary-health'
    lotsosets[18][1] = 'Health care'
    lotsosets[18][2] = 'Adam Kaufman'
    lotsosets[18][3] = '2015'
    lotsosets[18][4] = 'digital health'
    lotsosets[19][0] = 'cancer-genetics'
    lotsosets[19][1] = 'cancer'
    lotsosets[19][2] = 'genetics'
    lotsosets[19][3] = 'IPO'
    lotsosets[19][4] = 'New York'
    lotsosets[20][0] = 'cancer-care-trust'
    lotsosets[20][1] = 'health care'
    lotsosets[20][2] = 'children'
    lotsosets[20][3] = '2010'
    lotsosets[20][4] = 'dehli'
    lotsosets[21][0] = 'candiag'
    lotsosets[21][1] = '961K'
    lotsosets[21][2] = 'bloodtests'
    lotsosets[21][3] = '2010'
    lotsosets[21][4] = 'Software'
    lotsosets[22][0] = 'candidlab'
    lotsosets[22][1] = 'European Union'
    lotsosets[22][2] = 'Angel'
    lotsosets[22][3] = '2015'
    lotsosets[22][4] = 'fitness'
    lotsosets[23][0] = 'canna-hub'
    lotsosets[23][1] = 'cannabis'
    lotsosets[23][2] = 'children'
    lotsosets[23][3] = '2016'
    lotsosets[23][4] = 'Real Estate'
    lotsosets[24][0] = 'cannabis-sativa'
    lotsosets[24][1] = 'cannabis'
    lotsosets[24][2] = 'children'
    lotsosets[24][3] = '2005'
    lotsosets[24][4] = 'Nevada'
    lotsosets[25][0] = 'cannaregs'
    lotsosets[25][1] = 'cannabis'
    lotsosets[25][2] = 'Denver'
    lotsosets[25][3] = '2014'
    lotsosets[25][4] = 'Amanda Ostrowitz'
    lotsosets[26][0] = 'cannabis-sativa'
    lotsosets[26][1] = 'cannabis'
    lotsosets[26][2] = 'children'
    lotsosets[26][3] = '2005'
    lotsosets[26][4] = 'Nevada'
    lotsosets[27][0] = 'cannabis-sativa'
    lotsosets[27][1] = 'cannabis'
    lotsosets[27][2] = 'children'
    lotsosets[27][3] = '2005'
    lotsosets[27][4] = 'Nevada'
    lotsosets[28][0] = 'cannection'
    lotsosets[28][1] = 'cannabis'
    lotsosets[28][2] = 'dating'
    lotsosets[28][3] = '2008'
    lotsosets[28][4] = 'Camden Ramsay'
    lotsosets[29][0] = 'canon-staar'
    lotsosets[29][1] = 'Acquired'
    lotsosets[29][2] = 'eye implant'
    lotsosets[29][3] = '1988'
    lotsosets[29][4] = 'Tokyo'
    lotsosets[30][0] = 'canopy partners'
    lotsosets[30][1] = 'Greensboro'
    lotsosets[30][2] = 'East Coast'
    lotsosets[30][3] = '2010'
    lotsosets[30][4] = 'Medical Imaging'
    lotsosets[31][0] = 'CanSurround'
    lotsosets[31][1] = 'Biotechnology'
    lotsosets[31][2] = 'well-being'
    lotsosets[31][3] = '2013'
    lotsosets[31][4] = 'Debt Financing'
    lotsosets[32][0] = 'canopy partners'
    lotsosets[32][1] = 'Greensboro'
    lotsosets[32][2] = 'East Coast'
    lotsosets[32][3] = '2010'
    lotsosets[32][4] = 'Medical Imaging'
    lotsosets[33][0] = 'canopy partners'
    lotsosets[33][1] = 'Greensboro'
    lotsosets[33][2] = 'East Coast'
    lotsosets[33][3] = '2010'
    lotsosets[33][4] = 'Medical Imaging'







    def _init_(self):
      self.lotsosets = lotsosets








def main():
    output = modelworks()
    test = input("enter word")
    result = set()
    for i in range(34):
        for j in range(5):
            if output.lotsosets[i][j] == test:
                result.add(output.lotsosets[i][0]);
    for x in result:
        print(x)

if __name__ == "__main__":
    main()
